version: "3.7"

services:
  app:
    build: .
    scale: 8
    env_file: ./.env
  nginx:
    image: nginx:latest
    ports:
      - 8085:8085
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
